export const TEAMS = {
  RED: 'red',
  BLUE: 'blue',
  GREEN: 'green',
}

export const ROLES = {
  hacker: {
    key: 'hacker',
    name: 'Hacker',
    team: TEAMS.RED,
    image: 'hacker.png',
    nightOrder: 5,
    turnOneOnly: false,
    description: 'Chaque nuit, les Hackers choisissent un joueur à éliminer.',
  },
  hackerInfiltre: {
    key: 'hackerInfiltre',
    name: 'Hacker Infiltré',
    team: TEAMS.RED,
    image: 'hacker infiltré.png',
    nightOrder: 1,
    turnOneOnly: true,
    description: 'Peut échanger son identité avec une carte non distribuée. S\'il voit deux cartes Hacker, il doit en prendre une.',
  },
  administrateur: {
    key: 'administrateur',
    name: 'Administrateur Réseau',
    team: TEAMS.GREEN,
    image: 'administrateur réseau.png',
    nightOrder: 2,
    turnOneOnly: true,
    description: 'Lie deux joueurs. Si l\'un est éliminé, l\'autre l\'est aussi.',
  },
  analyste: {
    key: 'analyste',
    name: 'Analyste de Données',
    team: TEAMS.BLUE,
    image: 'analyst données.png',
    nightOrder: 4,
    turnOneOnly: false,
    description: 'Scanne un joueur pour connaître sa véritable identité.',
  },
  ingenieur: {
    key: 'ingenieur',
    name: 'Ingénieure Système',
    team: TEAMS.BLUE,
    image: 'ingénieur systeme.png',
    nightOrder: 6,
    turnOneOnly: false,
    description: 'Peut utiliser le Correctif (sauver la victime) ou le Contre-virus (éliminer un suspect). Chaque script une seule fois.',
  },
  agent: {
    key: 'agent',
    name: 'Agent de Cybersécurité',
    team: TEAMS.BLUE,
    image: 'agent de cybersécurité.png',
    nightOrder: null,
    turnOneOnly: false,
    description: 'S\'il est éliminé, il neutralise immédiatement un autre joueur.',
  },
  employe: {
    key: 'employe',
    name: 'Employé',
    team: TEAMS.GREEN,
    image: 'employé.png',
    nightOrder: null,
    turnOneOnly: false,
    description: 'Aucun privilège. Utilise son intuition pour voter.',
  },
  stagiaire: {
    key: 'stagiaire',
    name: 'Stagiaire IT',
    team: TEAMS.GREEN,
    image: 'stagiaireIT.png',
    nightOrder: null,
    turnOneOnly: false,
    description: 'Peut espionner les Hackers la nuit. Si repérée, elle est éliminée à la place de la victime.',
  },
  responsable: {
    key: 'responsable',
    name: 'Responsable',
    team: TEAMS.GREEN,
    image: null,
    nightOrder: null,
    turnOneOnly: false,
    description: 'Élu par le groupe. Son vote compte double. S\'il est éliminé, il désigne son successeur.',
  },
}

export const NIGHT_STEPS = [
  {
    key: 'hackerInfiltre',
    name: 'Hacker Infiltré',
    order: 1,
    turnOneOnly: true,
    inputType: 'centerCardSwap',
    instruction: 'Le Hacker Infiltré regarde les cartes du centre et peut en échanger une avec la sienne.',
  },
  {
    key: 'administrateur',
    name: 'Administrateur Réseau',
    order: 2,
    turnOneOnly: true,
    inputType: 'selectTwo',
    instruction: 'L\'Administrateur Réseau choisit deux joueurs à lier.',
  },
  {
    key: 'utilisateursLies',
    name: 'Utilisateurs Liés',
    order: 3,
    turnOneOnly: true,
    inputType: 'info',
    instruction: 'Les Utilisateurs Liés se reconnaissent.',
    requiresAdmin: true,
  },
  {
    key: 'analyste',
    name: 'Analyste de Données',
    order: 4,
    turnOneOnly: false,
    inputType: 'selectOne',
    instruction: 'L\'Analyste scanne un joueur pour découvrir son identité.',
  },
  {
    key: 'hackers',
    name: 'Les Hackers',
    order: 5,
    turnOneOnly: false,
    inputType: 'selectOneVictim',
    instruction: 'Les Hackers choisissent un joueur à éliminer. La Stagiaire IT peut tenter d\'observer.',
  },
  {
    key: 'ingenieur',
    name: 'Ingénieure Système',
    order: 6,
    turnOneOnly: false,
    inputType: 'engineerAction',
    instruction: 'L\'Ingénieure peut utiliser le Correctif (sauver) ou le Contre-virus (éliminer).',
  },
]
